### PR TITLE
Ltw ms

### PR DESCRIPTION
**Pull request by marlonShawDEV**

### CODE REVIEW

**Comment by SCarrero** [comment]
I don't think the last pull was marked after it was approved

**Comment by marlonShawDEV** [comment]
What do you mean by “was marked”?

Marlon Shaw
Web Content Developer Sr
Online and Creative Services
Corporate Communications and External Relations

Office: 703.903.2743
BB: 571.395.1412
Telecommute – Friday
[http://www.freddiemac.com/images/logos/fm_email_sig.png]

**Comment by SCarrero** [comment]
I changed it to "merged" 2 seconds after it posted.  Hard to see comments on my phone.

**Comment by marlonShawDEV** [comment]
Sherry - can you review and merge to master?

**Comment by SCarrero** [comment]
approved, but unable to merge into master due to conflicting files.

**Comment by marlonShawDEV** [comment]
Oh boy. Let me take a look at resolving the conflict.

Marlon Shaw
Web Content Developer Sr
Online and Creative Services
Corporate Communications and External Relations

Office: 703.903.2743
BB: 571.395.1412
Telecommute – Friday
[http://www.freddiemac.com/images/logos/fm_email_sig.png]

**Comment by SCarrero** [comment]
deleting the ltw-ms branch -- it has been merged into master.

**Pull request merged**
